### ISSUE TITLE
@mrcwinn Saabsite critical review

### ISSUE THREAD

**Issue by Rewinn** [Rewinn/Saab-Site#1]
I have completed Saabsite to the best of my current abilities.  Now, rip it to shreds!

Notes:

HTML --
1.  I still have to include Twitter card and Facebook meta info.
2. I am not passing html5 validation because I do not have an img src...not quite sure what to do about that.
2.5. I am getting validation errors for code I did not write, so I assume I shouldn't touch it.  Right?  I included a screenshot below.
3. I reduced the file sizes of my audio and don't think I can get it any smaller.  Do you think it's an issue?

CSS --
1. I significantly reduced my background image file size.  How is the quality on your desktop?
2. I'm not sure that I formatted the fullscreen gfycat in the smartest way.  It seems like a lot of code.  Is there a better way?
3. I checked my media queries with Chrome and my two devices.  How does it look on your watch?  hahaha.  

![screen shot 2015-04-30 at 2 56 27 pm](https://cloud.githubusercontent.com/assets/8756380/7421306/20d9b1b2-ef49-11e4-879a-d9ebd9ff2cad.png)

**Comment by mrcwinn** [comment]
1. Cool. Good to have that.
2. You can pass validation by setting the `src` to all the same image. Since these DIVs aren't visible without JS, I would make it a 1x1 pixel image — absolute minimum file size.
3. Sounds FAN-TASTIC.

CSS
1. Quality's fine. Honestly on my retina screen it looks like dogshit, but it sort of works because the GIFs are low quality, and so are the cars. Kidding!
2. It looks like necessary code to me.
3. It looks great on my Apple Watch, especially since it doesn't play music from websites!

**Comment by Rewinn** [comment]
1. I tried to increase the quality of the .jpg.
2. I added <src>
